config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 resources :posts
 
 root 'static_pages#index'

 get 'about' => 'static_pages#about'
 get 'faq' => 'static_pages#faq'
 get 'contact' => 'static_pages#contact'

 get 'new_post' => 'posts#new'
 
 
end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, presence: true
	validates :body, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:index]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post successful"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		if @post.save
			flash[:success] = "Post updated"
			redirect_to root_url
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to root_url
	end

	private

		def post_params
			params.require(:post).permit(:title,:body)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
		@post = Post.all
	end

	def about
	end

	def faq
	end

	def contact
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Bloggster", root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "About", about_path %></li>
        <li><%= link_to "Faq", faq_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <%else%>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<%= render 'layouts/nav' %>
		<% flash.each do |k,v| %>
			<div class="alert alert-<%= k %>"><%= v %></div>
		<% end %>

		<%= yield %>
	</div>
	
</body>
</html>

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>

	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |err| %>
			<li><%= err %></li>
		<% end %>
	<% end %>

	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>
	<p><%= f.label :body %></p>
	<p><%= f.text_area :body %></p>

	<p><%= f.submit "Submit", class:"btn btn-default" %></p>

<% end %>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>

	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |err| %>
			<li><%= err %></li>
		<% end %>
	<% end %>

	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>
	<p><%= f.label :body %></p>
	<p><%= f.text_area :body %></p>

	<p><%= f.submit "Submit", class:"btn btn-default" %></p>

<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/static_pages/faq.html.erb
<h1>Frequently Asked Questions</h1>

app/views/static_pages/index.html.erb
<%= link_to "New Post", new_post_path, class:"btn btn-default" %>

<% @post.each do |p| %>
	<h3><%= p.title %></h3>
	<h6>Posted by <%= p.user.email %></h6>
	<p><%= p.body %></p>

	<% if p.user == current_user %>
	<%= link_to "Edit", edit_post_path(p), class:"btn btn-default" %>
	<%= link_to "Delete", post_path(p), method: :delete, class:"btn btn-default", data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>